version: 2
jobs:
  build:
    working_directory: ~/vue-material-design-icons
    docker:
      - image: node:12-alpine
    steps:
      - run:
          name: Install certificate handling for artifact uploading
          command: apk add ca-certificates
      - checkout
      - run: 
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: coverage
