version: 2.1
defaults: &defaults
  working_directory: ~/ci
  resource_class: small
  docker:
    - image: cimg/node:lts
commands:
  install_deps:
    description: Install dependencies
    steps:
      - checkout
      - run: npm ci
jobs:
  test:
    <<: *defaults
    steps:
      - install_deps
      - run: npm run build
      - run: ./node_modules/.bin/jest --runInBand --ci
      - store_test_results:
          path: reports
  release:
    <<: *defaults
    steps:
      - install_deps
      - run: npm run build
      - run: npx semantic-release
workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
